apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: ghcr.io/baosystems/postgis:12-3.3
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "dhis"
        - name: POSTGRES_DB
          value: "dhis"
        - name: POSTGRES_PASSWORD
          value: "dhis"
        - name: PGPASSWORD
          value: "dhis"
        volumeMounts:
        - name: db-volume
          mountPath: /docker-entrypoint-initdb.d/
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - psql --no-password --quiet --username $$POSTGRES_USER postgres://127.0.0.1/$$POSTGRES_DB -p 5432 --command "SELECT 'ok'" > /dev/null
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 5
      volumes:
      - name: dump-volume
        persistentVolumeClaim:
          claimName: db-pvc
      - name: db-volume
        persistentVolumeClaim:
          claimName: db-pvc
