apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml convert
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/compose-default: "true"
        io.kompose.service: db
    spec:
      containers:
        - env:
            - name: PGPASSWORD
              value: dhis
            - name: POSTGRES_DB
              value: dhis
            - name: POSTGRES_PASSWORD
              value: dhis
            - name: POSTGRES_USER
              value: dhis
          image: ghcr.io/baosystems/postgis:12-3.3
          livenessProbe:
            exec:
              command:
                - psql --no-password --quiet --username $POSTGRES_USER postgres://127.0.0.1/$POSTGRES_DB -p 5432 --command "SELECT 'ok'" > /dev/null
            failureThreshold: 5
            initialDelaySeconds: 120
            periodSeconds: 1
            timeoutSeconds: 3
          name: db
          ports:
            - containerPort: 5432
              hostIP: 127.0.0.1
              hostPort: 5432
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
