apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: dhis2/core-dev:2.40
        ports:
        - containerPort: 8080
        env:
        - name: JAVA_OPTS
          value: >
            -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8081
            -Dlog4j2.configurationFile=/opt/dhis2/log4j2.xml
            -Dcom.sun.management.jmxremote
            -Dcom.sun.management.jmxremote.port=9010
            -Dcom.sun.management.jmxremote.local.only=false
            -Dcom.sun.management.jmxremote.authenticate=false
            -Dcom.sun.management.jmxremote.ssl=false
        volumeMounts:
        - name: dhis-conf
          mountPath: /opt/dhis2/dhis.conf
          subPath: dhis.conf
          readOnly: true
        - name: log4j-conf
          mountPath: /opt/dhis2/log4j2.xml
          subPath: log4j2.xml
          readOnly: true
      volumes:
      - name: dhis-conf
        configMap:
          name: dhis-conf
      - name: log4j-conf
        configMap:
          name: log4j2-config
