# Letsencrypt Production
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt
  # (Optional) Metadata
  # namespace: your-namespace
  namespace: istio-ingress
spec:
  acme:
    # Configure your email here
    email: simardeep.singh@phac-aspc.gc.ca
    preferredChain: ""
    # Letsencrypt Production
    privateKeySecretRef:
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          ingress:
            class: istio
      # - dns01:
      #     cloudDNS:
      #       # The ID of the GCP project
      #       project: phx-01h28kjpmp42v8xh59v0qvfpxa
        selector: {}
status: {}


---
# Letsencrypt Staging
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-staging
  # (Optional) Metadata
  # namespace: your-namespace
  namespace: istio-ingress
spec:
  acme:
    # Configure your email here...
    email: simardeep.singh@phac-aspc.gc.ca
    preferredChain: ""
    # Letsencrypt Statging
    privateKeySecretRef:
      name: letsencrypt-staging
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          ingress:
            class: istio
      # - dns01:
      #     cloudDNS:
      #       # The ID of the GCP project
      #       project: phx-01h28kjpmp42v8xh59v0qvfpxa
        selector: {}
status: {}


---
# Self-Signed Certificates
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  # (Optional) Metadata
  name: selfsigned
  # namespace: your-namespace
  namespace: istio-ingress
spec:
  selfSigned: {}
status: {}