apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: dhis2-postgis16-cluster-scheduled-backup
  namespace: dhis2
spec:
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  cluster:
    name: dhis2-postgis16-cluster